### ISSUE TITLE
`string_to_int` on multiple columns

### ISSUE THREAD

**Issue by pnezis** [tensorflow/transform#10]
Given a dataset with two categorical columns of the same feature type, is it possible to map them to an integer value using the same vocabulary? For example by applying `string_to_int` on the following toy dataset

```
previous_occupation, current_occupation
programmer, analyst
analyst, programmer
``` 

we get the transformed dataset

```
previous_occupation, current_occupation
0,0
1,1
```

I would like to get the following instead, given that the two columns contain the same feature type.

```
previous_occupation, current_occupation
0,1
1,0
```

**Comment by elmer-garduno** [comment]
You'll first need to make sure that you have a vocabulary that includes all the entries on both columns, then use that vocabulary to do the lookup, for example:

```python
    vocab = tft.uniques(tft.map(
        lambda x, y: tf.concat([x.values, y.values], 0),
        inputs['previous_occupation'], inputs['current_occupation']))

    def map_to_int(x, vocab):
      table = tf.contrib.lookup.string_to_index_table_from_tensor(vocab)
      return table.lookup(x)

    result['previous_occupation'] = tft.map(
        map_to_int, inputs['previous_occupation'], vocab)

    result['current_occupation'] = tft.map(
        map_to_int, inputs['current_occupation'], vocab)
```

**Comment by pnezis** [comment]
Thank you!

**Comment by lioutasb** [comment]
I'm trying to do the same with the following code (taken from the [Movielens](https://github.com/GoogleCloudPlatform/cloudml-samples/tree/master/movielens) example)

```
    genre_vocab = tft.uniques(tf.concat(
        [inputs[QUERY_RATED_CATEGORY_IDS].values,
         inputs[CANDIDATE_CATEGORY_IDS].values], 0))

    def map_to_int(x, vocabulary_or_file):
      """Maps string tensor into indexes using vocab.

      Args:
        x : a Tensor/SparseTensor of string.
        vocabulary_or_file: a Tensor/SparseTensor containing unique string
          values within x or a single value for the file where the vocabulary
          is stored.

      Returns:
        A Tensor/SparseTensor of indexes (int) of the same shape as x.
      """
      table = tfcontrib.lookup.index_table_from_tensor(mapping=vocabulary_or_file, num_oov_buckets=1)
      return table.lookup(x)

    result[QUERY_RATED_CATEGORY_IDS] = tft.apply_function(
        map_to_int, inputs[QUERY_RATED_CATEGORY_IDS], genre_vocab)
```

The code is very similar to the solution posted here but I get the following error. I tried doing it as described here as well but no luck. 

```
Traceback (most recent call last):
  File "preprocess.py", line 403, in <module>
    main()
  File "preprocess.py", line 400, in main
    preprocess(pipeline, args)
  File "preprocess.py", line 370, in preprocess
    | 'Analyze' >> beam_impl.AnalyzeDataset(preprocessing_fn))
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 820, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 488, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/pipeline.py", line 443, in apply
    return self.apply(transform, pvalueish)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/pipeline.py", line 479, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 174, in apply
    return m(transform, input)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 180, in apply_PTransform
    return transform.expand(input)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 670, in expand
    outputs = self._preprocessing_fn(impl_helper.copy_tensors(inputs))
  File "/home/billiout/test/tensorrec/movielens.py", line 254, in preprocessing_fn
    map_to_int, inputs[QUERY_RATED_CATEGORY_IDS], genre_vocab)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_transform/api.py", line 161, in apply_function
    return FunctionApplication(fn, args).user_output
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow_transform/api.py", line 89, in __init__
    output = fn(*args)
  File "/home/billiout/test/tensorrec/movielens.py", line 250, in map_to_int
    table = tfcontrib.lookup.index_table_from_tensor(mapping=vocabulary_or_file, num_oov_buckets=1)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/contrib/lookup/lookup_ops.py", line 138, in index_table_from_tensor
    name=name)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 1099, in index_table_from_tensor
    init, default_value, shared_name=shared_name, name=hash_table_scope)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 279, in __init__
    super(HashTable, self).__init__(table_ref, default_value, initializer)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 171, in __init__
    self._init = initializer.initialize(self)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/lookup_ops.py", line 350, in initialize
    table.table_ref, self._keys, self._values, name=scope)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/ops/gen_lookup_ops.py", line 386, in initialize_table_v2
    values=values, name=name)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/billiout/anaconda3/envs/py2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Shape must be rank 1 but is rank 0 for 'string_to_index/hash_table/table_init' (op: 'InitializeTableV2') with input shapes: [], [], [1].

```
I'm using the tensorflow-transform==0.6.0
