### ISSUE TITLE
Are there transforms for Image tasks like image classification or object detection?

### ISSUE THREAD

**Issue by aaronlelevier** [tensorflow/transform#119]
Hi,

Are there transforms for Image tasks like image classification or object detection?

I'm would like to use `tf.transform` for something very simple to learn and understand the library. How would I do something like normalize an image input Tensor for example that has pixel values of 0-255 to 0-1 for example in `tf.transform`? 

I have been trying to do an MNIST example. My code runs, but I have an empty `preprocessing_fn` here:

https://github.com/aaronlelevier/transform/blob/try_examples/examples/aaron_simple_example.py#L191

I am doing a `normalize` 0-1 in `_make_training_input_fn`, but I'm pretty sure that I need to move that to the `preprocessing_fn` so the `normalize` becomes part of the serving graph. 

When looking at the value of `inputs` in my current `preprocessing_fn` it's:

```
{u'image': <tf.Tensor 'inputs/inputs/image_copy:0' shape=(?,) dtype=string>, u'label': <tf.Tensor 'inputs/inputs/label_copy:0' shape=(?,) dtype=int64>}
```

I'm just not sure if I can do a `tf.transform` here using `tft.scale_to_0_1` or if I need to do more Beam Pipeline steps before running the `preprocessing_fn`. 

It seems like it needs to work with `tft.coders.ExampleProtoCoder(RAW_DATA_METADATA.schema)`.

I'm a little lost. Really enjoying `tf.Transform`. Any help is appreciated. Maybe some of this is built in to `tf.Tranform` and I just haven't found it. 

Thanks

**Comment by aaronlelevier** [comment]
I've still been poking around at this. Is the basic concept that the `preprocessing_fn` takes a dict of Tensors in and returns a dict of Tensors out?

For my MNIST example I'm trying to create, if the end User POSTs to the API an image with a 7 for example, this would be a byte string incoming to the [TensorFlow Serving](https://github.com/tensorflow/serving) API endpoint. So, does the Model itself take a byte string as input and convert to an image array for the Model then to do inference on? Or, is that what `preprocessing_fn` does in `tf.Transform` as a pre-input step and the Model should always take the image array as input?

Any help is appreciated. Thanks

Awesome work by the way. I've just been learning things left and right reading source files. Thank you!

**Comment by aaronlelevier** [comment]
Hi,

I have most recently changed `preprocessing_fn` to this:

```python
def preprocessing_fn(inputs):
  """
  Preprocess input columns into transformed columns.

  NOTE: empty func, not sure if tf.transforms does stuff for images...
  """
  features = tf.parse_single_example(
    inputs[IMAGE_KEY][0],
    features={
      IMAGE_KEY: tf.FixedLenFeature([], tf.string),
  })
  # Convert from a scalar string tensor (whose single string has
  image = tf.decode_raw(features[IMAGE_KEY], tf.uint8)
  image.set_shape((mnist.IMAGE_PIXELS))  # 784
  image = tf.reshape(image, (HEIGHT, WIDTH))
  image = tf.cast(image, tf.float32) * (1. / 255) - 0.5
  inputs[IMAGE_KEY] = image
  return inputs
```

When using `pdb` to inspect  what the value of `inputs` is before the function returns, I get the following. This looks valid:

```
{u'image': <tf.Tensor 'sub:0' shape=(28, 28) dtype=float32>,
 u'label': <tf.Tensor 'inputs/inputs/label_copy:0' shape=(?,) dtype=int64>}
```

So it looks valid, like I'm converting the numpy array byte string correctly to a float Tensor with shape (28, 28). But, when I run the full file, I get a fail and a large stacktrace. The final output of the stacktrace still shows the numpy byte string. But I thought the `preprocessing_fn` output would be used. Maybe I'm misunderstanding the `tf.Transform` hook for this?

Sorry to bother you all. Just still stuck, so any help is much appreciated. Thanks

Here's the stacktrace:

```
2019-05-12 08:25:21.229477: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/tensorflow/python/saved_model/signature_def_utils_impl.py:205: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
WARNING:tensorflow:From /Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/tensorflow/python/saved_model/signature_def_utils_impl.py:205: build_tensor_info (from tensorflow.python.saved_model.utils_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This function will only be available through the v1 compatibility library as tf.compat.v1.saved_model.utils.build_tensor_info or tf.compat.v1.saved_model.build_tensor_info.
PCollection[AnalyzeAndTransform/TransformDataset/ConvertAndUnbatch.None]
2019-05-12 08:25:21.628503: W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at example_parsing_ops.cc:240 : Invalid argument: Could not parse example input, value: '
ERROR:tensorflow:Could not parse example input, value: ' while applying transform function for tensors [u'image', u'label']
ERROR:tensorflow:Could not parse example input, value: ' while applying transform function for tensors [u'image', u'label']
Traceback (most recent call last):
  File "examples/aaron_simple_example.py", line 475, in <module>
    main()
  File "examples/aaron_simple_example.py", line 468, in main
    transform_data(working_dir)
  File "examples/aaron_simple_example.py", line 215, in transform_data
    print(transformed_train_data)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/pipeline.py", line 426, in __exit__
    self.run().wait_until_finish()
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/pipeline.py", line 406, in run
    self._options).run(False)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/pipeline.py", line 419, in run
    return self.runner.run_pipeline(self, self._options)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/direct/direct_runner.py", line 132, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 276, in run_pipeline
    default_environment=self._default_environment))
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 280, in run_via_runner_api
    return self.run_stages(*self.create_stages(pipeline_proto))
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 356, in run_stages
    stage_context.safe_coders)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 511, in run_stage
    data_input, data_output)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 1217, in process_bundle
    result_future = self._controller.control_handler.push(process_bundle)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 832, in push
    response = self.worker.do_instruction(request)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 312, in do_instruction
    request.instruction_id)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/worker/sdk_worker.py", line 331, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 554, in process_bundle
    ].process_encoded(data.data)
  File "/Users/aaron/Documents/github/transform/venv/lib/python2.7/site-packages/apache_beam/runners/worker/bundle_processor.py", line 140, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 245, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 246, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 142, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 396, in apache_beam.runners.worker.operations.ImpulseReadOperation.process
  File "apache_beam/runners/worker/operations.py", line 403, in apache_beam.runners.worker.operations.ImpulseReadOperation.process
  File "apache_beam/runners/worker/operations.py", line 246, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 142, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 560, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 561, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 740, in apache_beam.runners.common.DoFnRunner.receive
  File "apache_beam/runners/common.py", line 746, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 785, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 744, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 422, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 870, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 142, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 560, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 561, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 740, in apache_beam.runners.common.DoFnRunner.receive
  File "apache_beam/runners/common.py", line 746, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 785, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 744, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 422, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "apache_beam/runners/common.py", line 870, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 142, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 560, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 561, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 740, in apache_beam.runners.common.DoFnRunner.receive
  File "apache_beam/runners/common.py", line 746, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 800, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 744, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 563, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 630, in apache_beam.runners.common.PerWindowInvoker._invoke_per_window
  File "apache_beam/runners/common.py", line 831, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/common.py", line 846, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/Users/aaron/Documents/github/transform/tensorflow_transform/beam/impl.py", line 444, in process
    yield self._handle_batch(batch)
  File "/Users/aaron/Documents/github/transform/tensorflow_transform/beam/impl.py", line 396, in _handle_batch
    raise ValueError('bad inputs: {}'.format(feed_list))
ValueError: bad inputs: [["\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00C\xe8'\x00\x00\x00\x00\x00\x00\x00\x00\x00>Q\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x\xb4'\x00\x00\x00\x00\x00\x00\x00\x00\x00~\xa3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x99\xd2(\x00\x00\x00\x00\x00\x00\x00\x00\x00\xdc\xa3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x1b\xfe\xa2\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xde\xa3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb7\xfe}\x00\x00\x00\x00\x00\x00\x00\x00\x00.\xf5\xa3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xc6\xfe8\x00\x00\x00\x00\x00\x00\x00\x00\x00x\xfe\xa3\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x17\xe7\xfe\x1d\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9f\xfex\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa3\xfe\xd8\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9f\xfeC\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0eV\xb2\xf8\xfe[\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x9f\xfeU\x00\x00\x00/1t\x90\x96\xf1\xf3\xea\xb3\xf1\xfc(\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x96\xfd\xed\xcf\xcf\xcf\xfd\xfe\xfa\xf0\xc6\x8f[\x1c\x05\xe9\xfa\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00w\xb1\xb1\xb1\xb1\xb1b8\x00\x00\x00\x00\x00f\xfe\xdc\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa9\xfe\x89\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa9\xfe9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa9\xfe9\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa9\xff^\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa9\xfe`\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa9\xfe\x99\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa9\xff\x99\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`\xfe\x99\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"], [4L]] [while running 'AnalyzeAndTransform/TransformDataset/Transform']
Exception TypeError: TypeError("'NoneType' object is not callable",) in <bound method Session.__del__ of <tensorflow.python.client.session.Session object at 0x12110bc50>> ignored
```

**Comment by aaronlelevier** [comment]
I think this is User error. I found some more documentation, so I'm going to read through it. Please disregard. Thanks

**Comment by K-Niu** [comment]
@aaronlelevier Wondering if you ever figured out your `ValueError: bad inputs:` error? I am working on a very similar pipeline to yours, dealing with images.

I am trying to normalize images and my preprocessing function is something like this
```
def preprocessing_fn(input):
    def preprocess_image(image_bytes):
        image = tf.image.decode_jpeg(image_bytes, channels=3)
        image = tf.image.resize(image, [IMAGE_HEIGHT, IMAGE_WIDTH])

        return image

    # Tensorflow transform applies transform functions in batches
    images = tf.map_fn(preprocess_image, input["image_bytes"])

    return {
        "image": tft.scale_to_0_1(images),
    }
```
but getting the `ValueError: bad inputs:` error with a bunch of bytes as well.
