### ISSUE TITLE
Some analyzers error with `Tensor had invalid shape () for FixedLenFeature: must have rank at least 1` when returning results in AnalyzeAndTransformDataset

### ISSUE THREAD

**Issue by joshbarth** [tensorflow/transform#128]
Certain analyzers, like tft.max, tft.min, tft.mean, and tft.vocabulary give a
```ValueError: Tensor("vocabulary/Placeholder:0", shape=(), dtype=string) had invalid shape () for FixedLenFeature: must have rank at least 1```
when returned via AnalyzeAndTransformDataset like this:
```python
        def preprocessing_inputs_fn(inputs):
            values = inputs["Values"]
            test = tft.max(values)
            return {
                "test": test
            }
with beam.Pipeline() as pipeline:
    with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
       raw_dataset = load_csv(pipeline)

        transformed_inputs_dataset, transform_input_fn = (
               raw_dataset
               | tft_beam.AnalyzeAndTransformDataset(preprocessing_inputs_fn))

        self.save_tf_record(transformed_inputs_dataset)

        tf_transform_output = tft.TFTransformOutput(self.working_dir)

        def input_fn():
            dataset = tf.data.experimental.make_batched_features_dataset(
                file_pattern=os.path.join(self.working_dir, self.transform_data_file) + "*",
                batch_size=self.batch_size,
                features=tf_transform_output.transformed_feature_spec(),
                reader=tf.data.TFRecordDataset,
                shuffle=self.shuffle)

            transformed_features = tf.compat.v1.data.make_one_shot_iterator(
                dataset).get_next()

            transformed_labels = {}
            for i in transformed_features:
                if i.startswith("label-"):
                    transformed_labels[i[6:]] = transformed_features[i]

            return transformed_features, transformed_labels

        return input_fn
```
The full stack is 
```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/josh/workspace/VisibleAIUtils/tests/test_tensorflow_data_transforms.py", line 84, in test_group_by
    test_fn = csv_loader.load_and_transform_csv()
  File "/Users/josh/workspace/VisibleAIUtils/VisibleAIUtils/tensorflow_load_data.py", line 118, in load_and_transform_csv
    | tft_beam.AnalyzeAndTransformDataset(self.transform_inputs_fn))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/transforms/ptransform.py", line 510, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 516, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/runner.py", line 193, in apply
    return m(transform, input, options)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/runner.py", line 199, in apply_PTransform
    return transform.expand(input)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 872, in expand
    dataset | 'AnalyzeDataset' >> AnalyzeDataset(self._preprocessing_fn))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/transforms/ptransform.py", line 896, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/transforms/ptransform.py", line 510, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 480, in apply
    return self.apply(transform, pvalueish)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 516, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/runner.py", line 193, in apply
    return m(transform, input, options)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/runner.py", line 199, in apply_PTransform
    return transform.expand(input)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 825, in expand
    input_metadata))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 761, in expand
    schema=schema_inference.infer_feature_schema(output_signature, graph))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/schema_inference.py", line 121, in infer_feature_schema
    feature_spec = _feature_spec_from_batched_tensors(features)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/schema_inference.py", line 67, in _feature_spec_from_batched_tensors
    'at least 1'.format(tensor, shape))
ValueError: Tensor("vocabulary/Placeholder:0", shape=(), dtype=string) had invalid shape () for FixedLenFeature: must have rank at least 1
```
This is also affecting a customer analyzer I wrote to try to get unique values without generating a vocabulary file, but the exact stack is slightly different:
```
Error
Traceback (most recent call last):
  File "apache_beam/runners/common.py", line 751, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 423, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/transforms/core.py", line 1265, in <lambda>
    wrapper = lambda x: [fn(x)]
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 656, in _infer_metadata_from_saved_model
    schema=schema_inference.infer_feature_schema(outputs, graph, session))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/schema_inference.py", line 121, in infer_feature_schema
    feature_spec = _feature_spec_from_batched_tensors(features)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/schema_inference.py", line 67, in _feature_spec_from_batched_tensors
    'at least 1'.format(tensor, shape))
ValueError: Tensor("transform/Const_8:0", shape=(), dtype=string) had invalid shape () for FixedLenFeature: must have rank at least 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/josh/workspace/VisibleAIUtils/tests/test_tensorflow_data_transforms.py", line 84, in test_group_by
    test_fn = csv_loader.load_and_transform_csv()
  File "/Users/josh/workspace/VisibleAIUtils/VisibleAIUtils/tensorflow_load_data.py", line 124, in load_and_transform_csv
    return self.get_input_fn()
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 426, in __exit__
    self.run().wait_until_finish()
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 406, in run
    self._options).run(False)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/pipeline.py", line 419, in run
    return self.runner.run_pipeline(self, self._options)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/direct/direct_runner.py", line 128, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 277, in run_pipeline
    default_environment=self._default_environment))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 281, in run_via_runner_api
    return self.run_stages(*self.create_stages(pipeline_proto))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 357, in run_stages
    stage_context.safe_coders)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 521, in run_stage
    data_input, data_output)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 1227, in process_bundle
    result_future = self._controller.control_handler.push(process_bundle)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/portability/fn_api_runner.py", line 842, in push
    response = self.worker.do_instruction(request)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 333, in do_instruction
    request.instruction_id)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 359, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 589, in process_bundle
    ].process_encoded(data.data)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 143, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 246, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 247, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 143, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 419, in apache_beam.runners.worker.operations.ImpulseReadOperation.process
  File "apache_beam/runners/worker/operations.py", line 426, in apache_beam.runners.worker.operations.ImpulseReadOperation.process
  File "apache_beam/runners/worker/operations.py", line 247, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 143, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 583, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 584, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 747, in apache_beam.runners.common.DoFnRunner.receive
  File "apache_beam/runners/common.py", line 753, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 792, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "apache_beam/runners/common.py", line 751, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 563, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 630, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 838, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/common.py", line 877, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "apache_beam/runners/worker/operations.py", line 100, in apache_beam.runners.worker.operations.ConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 583, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 584, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 747, in apache_beam.runners.common.DoFnRunner.receive
  File "apache_beam/runners/common.py", line 753, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 807, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/future/utils/__init__.py", line 421, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 751, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 423, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/apache_beam/transforms/core.py", line 1265, in <lambda>
    wrapper = lambda x: [fn(x)]
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/beam/impl.py", line 656, in _infer_metadata_from_saved_model
    schema=schema_inference.infer_feature_schema(outputs, graph, session))
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/schema_inference.py", line 121, in infer_feature_schema
    feature_spec = _feature_spec_from_batched_tensors(features)
  File "/Users/josh/workspace/VisibleAIUtils/venv/lib/python3.6/site-packages/tensorflow_transform/schema_inference.py", line 67, in _feature_spec_from_batched_tensors
    'at least 1'.format(tensor, shape))
ValueError: Tensor("transform/Const_8:0", shape=(), dtype=string) had invalid shape () for FixedLenFeature: must have rank at least 1 [while running 'AnalyzeAndTransformDataset/AnalyzeDataset/ComputeDeferredMetadata']
```
The custom analyzer used there is nearly the same as the built in vocabulary method, only with a custom node that converts the results to an AnalyzerDef node instead of the last step writing to a file. Interestingly, this method should actually return more than one value, unlike the max and mean functions.

Is this error intended behavior? Am I missing something that will allow me to return the result of methods like these, or is this a bug?

**Comment by joshbarth** [comment]
Figured it out. In order to return any values from those functions you have to call `tf.reshape()`. So the example I posted will work by just changing `tft.max(values)` to `tf.reshape(tft.max(values), [-1])`. That fixed my custom analyzer also. I will close this issue.

**Comment by AnandInguva** [comment]
> tf.reshape(tft.max(values), [-1])

Worked for me too. Thanks
