### ISSUE TITLE
 Incompatible shapes when saving a Keras model

### ISSUE THREAD

**Issue by tillwf** [tensorflow/transform#194]
Hello,

An issue has been opened in the TFRanking repo ([#218](https://github.com/tensorflow/ranking/issues/218)), but it seems there hasn't been that much activity recently. As it is related to TFTransform, does someone has a any clue of what is wrong ?

As a summary, we are working on a training pipeline using TFTransform and TFRanking (https://github.com/phaidara/tfranking-example) and the transformation of VarLenFeatures breaks the model saving in TFRanking.

```
./train_keras_model.py:81 serve_tf_examples_fn  *
        transformed_features = model.tft_layer(parsed_features)
    /../../../../../venv/lib/python3.5/site-packages/tensorflow_transform/output_wrapper.py:303 call  *
        return self._saved_model_loader.apply_v1_transform_model_in_v2(inputs)
    ../../../../../../venv/lib/python3.5/site-packages/tensorflow_transform/saved/saved_transform_io_v2.py:155 apply_v1_transform_model_in_v2  *
        tensor.shape.assert_is_compatible_with(input_map[name].shape)
    ../../../../../venv/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with  **
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))
    ValueError: Shapes (2,) and (3,) are incompatible
```

Thank you for your help

**Comment by zoyahav** [comment]
It looks like TFRanking is producing a 3D SparseTensor in `serve_tf_examples_fn` which is not supported in tf.Transform (only 2D is supported).
We should make sure to document this limitation better, I believe right now we just have this TODO here:
https://github.com/tensorflow/transform/blob/92bf190485aa8efbaba418b944da2f9399107c90/tensorflow_transform/impl_helper.py#L326
But this is unlikely to be supported in the near future.

If you could format the SparseTensor in `serve_tf_examples_fn` as 2D, or get the TFRanking to parse it as 2D, then it should work.

**Comment by tillwf** [comment]
Thank you very much for your quick answer. We're going to investigate your solution. Should I close the issue ?

**Comment by zoyahav** [comment]
Closing it now, feel free to re-open or just open a new one if you encounter any other issues.

**Comment by tillwf** [comment]
Hello @zoyahav,

Just to give you a little feedback: Your idea worked, we do not have the error anymore. Thanks a lot.
We only have a strange `Exception Ignored` just after the prediction process.

```
Exception ignored in: <function CapturableResourceDeleter.__del__ at 0x7f7d83858d08>
Traceback (most recent call last):
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/training/tracking/tracking.py", line 202, in __del__
    self._destroy_resource()
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 237, in restored_function_body
    return _call_concrete_function(function, inputs)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/function_deserialization.py", line 74, in _call_concrete_function
    result = function._call_flat(tensor_inputs, function._captured_inputs)  # pylint: disable=protected-access
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/saved_model/load.py", line 106, in _call_flat
    cancellation_manager)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1938, in _call_flat
    flat_outputs = forward_function.call(ctx, args_with_tangents)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 579, in call
    executor_type=executor_type)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/ops/functional_ops.py", line 1192, in partitioned_call
    f.add_to_graph(graph)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 495, in add_to_graph
    g._add_function(self)
  File "/home/till/tfranking_recommender/venv/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 3345, in _add_function
    gradient)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'func' argument to TF_GraphCopyFunction cannot be null

```

Apart from that, we noticed that adding the "examples" categorical features (not the categorical features in the "context"), decreases the overhaul performances.

We suspect the method `tft_layer` to wrongly embed these features (but not the one in the "context").

Does it seem possible ? We did not manage to display the features after the transformation, so we are not sure.

Thank you again.

**Comment by tillwf** [comment]
Should I re-open this issue or create a new one ? Thank you !

**Comment by zoyahav** [comment]
Please do create a new one with all the needed information such as a repro (ideally in the form of a colab notebook), versions used, etc.
