### ISSUE TITLE
Census_example with newly TFX_bsl code throws TypeCheckError + CSV Beam Pipeline Input

### ISSUE THREAD

**Issue by erikinfo** [tensorflow/transform#203]
TensorFlow version: 2.3.0
TFX version: 0.23.0
TFX_bsl: 0.23.0

also tested on 2.3/0.24.1/0.24.1

My goal is to read my CSV file in the beam Pipeline. So any other way that is working would help. 

```

with beam.Pipeline() as pipeline:
    with tft_beam.Context(temp_dir=tempfile.mkdtemp()):
            
            csv_tfxio = tfxio.BeamRecordCsvTFXIO(
                  physical_format='text',
                  column_names=CSV_col,
                  schema=raw_metadata.schema, delimiter=',')


            raw_data = (
                   pipeline
                    | 'ReadTrainData' >> beam.io.ReadFromText(input_path, coder=beam.coders.BytesCoder())
                    | 'FixCommasTrainData' >> beam.Map(lambda line: line.replace(b', ', b','))
                    | 'ToRecordBatches' >> csv_tfxio.BeamSource()) 
```

When trying this [newly commited](https://github.com/tensorflow/transform/commit/5feefe99db2ac1c714b1f81980863e14b1d1055c) way with my data i get the following error: 
```
[...]
---------------------------------------------------------------------------
TypeCheckError                            Traceback (most recent call last)
<ipython-input-56-6647c519ff0b> in <module>()
----> 1 encode()

47 frames
/usr/local/lib/python3.6/dist-packages/apache_beam/transforms/ptransform.py in type_check_inputs(self, pvalueish)
    871                   actual_type=bindings[arg],
    872                   arg=arg,
--> 873                   debug_str=type_hints.debug_str()))
    874 
    875   def _process_argspec_fn(self):

TypeCheckError: Type hint violation for 'ApplySavedModel': requires Union[List[Dict[Any, Union[List[Any], bytes, float, generic, int, ndarray, str]]], RecordBatch] but got List[RecordBatch] for batch
Full type hint:
IOTypeHints[inputs=((Union[List[Dict[Any, Union[List[Any], bytes, float, generic, int, ndarray, str]]], RecordBatch], <class 'str'>), {}), outputs=((Dict[str, Union[SparseTensorValue, ndarray]],), {})]
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/usr/local/lib/python3.6/dist-packages/tensorflow_transform/beam/impl.py", line 189, in <module>
    class _RunMetaGraphDoFn(beam.DoFn):
File "/usr/local/lib/python3.6/dist-packages/apache_beam/typehints/decorators.py", line 896, in annotate_input_types
    *converted_positional_hints, **converted_keyword_hints)

based on:
  IOTypeHints[inputs=None, outputs=((Dict[str, Union[SparseTensorValue, ndarray]],), {})]
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_transform/beam/impl.py", line 189, in <module>
      class _RunMetaGraphDoFn(beam.DoFn):
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/typehints/decorators.py", line 983, in annotate_output_types
      f._type_hints = th.with_output_types(return_type_hint)  # pylint: disable=protected-access


```

This is not the only problem, moreover the next part is also not working. 

```
raw_dataset = (raw_data, csv_tfxio.TensorAdapterConfig())
            transformed_data, transform_fn = (
                    raw_dataset | tft_beam.AnalyzeAndTransformDataset(preprocessing_fn))

```
```
[...]
AttributeError: 'TensorAdapterConfig' object has no attribute 'schema'
```

1. How to get around the TypeCheckError? It seems like there is one part missing but i cant figure out what. 
2. What are alternative ways that i can use?

**Comment by zoyahav** [comment]
Do you perhaps need to use `tfxio.CsvTFXIO` instead of `tfxio.BeamRecordCsvTFXIO`?
Note that in the new documentation, it is explained that the example should have been using `tfxio.CsvTFXIO` if the data didn't require additional manipulation:

> Note that we had to do some additional fix-ups after the CSV lines are read in. Otherwise, we could rely on the CsvTFXIO to handle both reading the files and translating to RecordBatches:
> 
> ```
> csv_tfxio = tfxio.CsvTFXIO(train_data_file, column_name=ordered_columns,
>                            schema=SCHEMA)
> record_batches = p | 'TFXIORead' >> csv_tfxio.BeamSource()
> tensor_adapter_config = csv_tfxio.TensorAdapterConfig()
> ```

https://github.com/tensorflow/transform/blob/master/docs/get_started.md#example-census-income-dataset

To answer your question about the TypeCheckError, it seems like you're passing TFT a PCollection of `List[RecordBatch]` while it expects `RecordBatch`.

To figure out both issues you're facing, could you please include more of your pipeline code?
For the second issue, could you please provide a full traceback?

**Comment by arghyaganguly** [comment]
Closing this due to inactivity.Please feel free to reopen with the requested information.
