### ISSUE TITLE
TukeyHHAnalyzers test cases fail on s390x architecture due to tolerance issue

### ISSUE THREAD

**Issue by rposts** [tensorflow/transform#213]
Tensorflow Transform: v0.26.0
OS: Ubuntu: 18.04/20.04

Following test cases fail on s390x architecture:
```
testTukeyHHAnalyzersWithDenseInputstukey_float32in_reduce
testTukeyHHAnalyzersWithSparseInputs_float32in_reduce
```

Here is a snippet of failure:
```
======================================================================
FAIL: testTukeyHHAnalyzersWithSparseInputs_float32in_reduce (tensorflow_transform.beam.tukey_hh_params_integration_v2_test.TukeyHHParamsIntegrationV2Test)
tensorflow_transform.beam.tukey_hh_params_integration_v2_test.TukeyHHParamsIntegrationV2Test.testTukeyHHAnalyzersWithSparseInputs_float32in_reduce
testTukeyHHAnalyzersWithSparseInputs_float32in_reduce(input_dtype=tf.float32, output_dtypes={'tukey_location': tf.float32, 'tukey_scale': tf.float32, 'tukey_hl': tf.float32, 'tukey_hr': tf.float32}, elementwise=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/absl/testing/parameterized.py", line 282, in bound_param_test
    return test_method(self, **testcase_params)
  File "/home/transform/tensorflow_transform/beam/tukey_hh_params_integration_test.py", line 494, in testTukeyHHAnalyzersWithSparseInputs
    beam_pipeline=beam.Pipeline())
  File "/home/transform/tensorflow_transform/beam/tukey_hh_params_integration_v2_test.py", line 49, in assertAnalyzerOutputs
    self).assertAnalyzerOutputs(*args, **kwargs)
  File "/home/transform/tensorflow_transform/beam/tft_unit.py", line 221, in assertAnalyzerOutputs
    force_tf_compat_v1=force_tf_compat_v1)
  File "/home/transform/tensorflow_transform/beam/tukey_hh_params_integration_v2_test.py", line 42, in assertAnalyzeAndTransformResults
    self).assertAnalyzeAndTransformResults(*args, **kwargs)
  File "/home/transform/tensorflow_transform/beam/tft_unit.py", line 346, in assertAnalyzeAndTransformResults
    self.assertDataCloseOrEqual(expected_data, transformed_data)
  File "/home/transform/tensorflow_transform/test_case.py", line 285, in assertDataCloseOrEqual
    raise e
  File "/home/transform/tensorflow_transform/test_case.py", line 281, in assertDataCloseOrEqual
    self._assertValuesCloseOrEqual(a_value, b_value, msg=msg)
  File "/home/transform/tensorflow_transform/test_case.py", line 294, in _assertValuesCloseOrEqual
    self.assertAllClose(a_value, b_value)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/test_util.py", line 1218, in decorated
    return f(*args, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/test_util.py", line 2607, in assertAllClose
    self._assertAllCloseRecursive(a, b, rtol=rtol, atol=atol, msg=msg)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/test_util.py", line 2567, in _assertAllCloseRecursive
    (path_str, path_str, msg)))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/test_util.py", line 2502, in _assertArrayLikeAllClose
    a, b, rtol=rtol, atol=atol, err_msg="\n".join(msgs), equal_nan=True)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 1533, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "/usr/local/lib/python3.6/dist-packages/numpy/testing/_private/utils.py", line 846, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
**Not equal to tolerance rtol=1e-06, atol=1e-06
Mismatched value: a is different from b. 
not close lhs = 0.0
not close rhs = 7.62939453125e-06
not close dif = 7.62939453125e-06**
not close tol = 1.0000076293945312e-06
dtype = float64, shape = ()
Mismatched elements: 1 / 1 (100%)
Max absolute difference: 7.62939453e-06
Max relative difference: 1.
 x: array(0.)
 y: array(7.629395e-06) : Row 0, key tukey_location
Compared:
[{'tukey_location': array(0., dtype=float32), 'tukey_scale': array(572.27765, dtype=float32), 'tukey_hl': array(0., dtype=float32), 'tukey_hr': array(0., dtype=float32)}, {'tukey_location': array(0., dtype=float32), 'tukey_scale': array(572.27765, dtype=float32), 'tukey_hl': array(0., dtype=float32), 'tukey_hr': array(0., dtype=float32)}, {'tukey_location': array(0., dtype=float32), 'tukey_scale': array(572.27765, dtype=float32), 'tukey_hl': array(0., dtype=float32), 'tukey_hr': array(0., dtype=float32)}]
vs.
[{'tukey_scale': array(572.2776, dtype=float32), 'tukey_location': array(7.6293945e-06, dtype=float32), 'tukey_hr': array(0., dtype=float32), 'tukey_hl': array(0., dtype=float32)}, {'tukey_scale': array(572.2776, dtype=float32), 'tukey_location': array(7.6293945e-06, dtype=float32), 'tukey_hr': array(0., dtype=float32), 'tukey_hl': array(0., dtype=float32)}, {'tukey_scale': array(572.2776, dtype=float32), 'tukey_location': array(7.6293945e-06, dtype=float32), 'tukey_hr': array(0., dtype=float32), 'tukey_hl': array(0., dtype=float32)}]

----------------------------------------------------------------------
```

It appears that default tolerance is too tight on s390x or possibly there is a bug that surfaces on this arch.  I tried making the following change and it makes the test cases pass but I can't be sure if this is the right thing to do:

```
diff --git a/tensorflow_transform/test_case.py b/tensorflow_transform/test_case.py
index 936481a..a2afddb 100644
--- a/tensorflow_transform/test_case.py
+++ b/tensorflow_transform/test_case.py
@@ -291,7 +291,7 @@ class TransformTestCase(parameterized.TestCase, tf.test.TestCase):
         isinstance(a_value, np.ndarray) and a_value.dtype == np.object):
       self.assertAllEqual(a_value, b_value)
     else:
-      self.assertAllClose(a_value, b_value)
+      self.assertAllClose(a_value, b_value, rtol=7.8e-06, atol=7.8e-06)

   def AssertVocabularyContents(self, vocab_file_path, file_contents):
     if vocab_file_path.endswith('.tfrecord.gz'):
```

Any input highly appreciated.

Thanks.

**Comment by zoyahav** [comment]
It is in fact a tolerance issue which could be resolved by adding tolerance knobs to TFT's test_case.
For our understanding, what's the reason for wanting these tests to pass on s390x?

**Comment by rposts** [comment]
Thanks @zoyahav for your comments.

The idea is to maintain parity with x86 arch so that Transform is functionally equivalent on s390x.  To that end we mostly rely on successful test case execution as long as it is not constrained to a specific architecture.  If you think these test cases are not applicable on non-x86 arch I can mark it as such on my side.  I have seen TensorFlow using flags such as `no_oss` to limit the execution of certain test cases.

Thanks.

**Comment by rposts** [comment]
Closing - adjusting tolerance resolves it.
