### ISSUE TITLE
TFX Transform component reports ValueError "The preprocessing function returned an empty dict"

### ISSUE THREAD

**Issue by abkanal18** [tensorflow/transform#238]
Transform component in TFX pipeline reports ValueError "The preprocessing function returned an empty dict". Sometimes the error disappears if I re-run the same pipeline without any changes. Recently it happens more frequently for some reason.

Here's the preprocessing function

```
def preprocess_eval(input_features):
    return input_features
```

Here's traceback

```
Traceback (most recent call last):
  File "local_runner.py", line 115, in <module>
    run()
  File "local_runner.py", line 110, in run
    enable_cache=False))
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tfx/orchestration/local/local_dag_runner.py", line 129, in run
    component_launcher.launch()
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 412, in launch
    executor_output = self._run_executor(execution_info)
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tfx/orchestration/portable/launcher.py", line 306, in _run_executor
    executor_output = self._executor_operator.run_executor(execution_info)
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 112, in run_executor
    execution_info.exec_properties)
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 466, in Do
    self.Transform(label_inputs, label_outputs, status_file)
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 985, in Transform
    len(analyze_data_paths))
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tfx/components/transform/executor.py", line 1119, in _RunBeamImpl
    preprocessing_fn, pipeline=pipeline))
  File "/Users/gxiao/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 1058, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/Users/gxiao/.local/lib/python3.7/site-packages/apache_beam/transforms/ptransform.py", line 573, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/Users/gxiao/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 646, in apply
    return self.apply(transform, pvalueish)
  File "/Users/gxiao/.local/lib/python3.7/site-packages/apache_beam/pipeline.py", line 689, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish, self._options)
  File "/Users/gxiao/.local/lib/python3.7/site-packages/apache_beam/runners/runner.py", line 188, in apply
    return m(transform, input, options)
  File "/Users/gxiao/.local/lib/python3.7/site-packages/apache_beam/runners/runner.py", line 218, in apply_PTransform
    return transform.expand(input)
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tensorflow_transform/beam/impl.py", line 1182, in expand
    self).expand(self._make_parent_dataset(dataset))
  File "/Users/gxiao/miniconda3/envs/lingo/lib/python3.7/site-packages/tensorflow_transform/beam/impl.py", line 1049, in expand
    raise ValueError('The preprocessing function returned an empty dict')
ValueError: The preprocessing function returned an empty dict
```
Try to check the source code and it seems to be related to structured_outputs of ConcreteFunction class is empty for some reason. Any idea how to fix it?

**Comment by abkanal18** [comment]
@varshaan @zoyahav

**Comment by zoyahav** [comment]
The error suggests that input_features is an empty dict, which suggests that perhaps the metadata/schema is empty, could you please check that and let us know what the schema looks like?
Is the schema always the same for all of these runs?

**Comment by glenxiao** [comment]
Good question. In this case, I'm using a TFX pipeline and TF Transform is one step of it (standard Transform component). The schema argument of Transform component is the output of `SchemaGen` component. Prior to `SchemaGen`, there's a `ExampleGen` (a custom component implemented from `QueryBasedExampleGen`) that ingests data from BigQuery, does some preprocessing with Beam pipeline, transfer all data into tf.Examples, and pass it to downstream components. 
I used a constant sql to fetch data from BigQuery, so the input data may be (more or less) the same. I assume the schema should stay relatively stable. 

Please let me know if any other questions. Thanks!

**Comment by zoyahav** [comment]
Thanks, since the schema is generated automatically for each iteration, could you please provide the schema for an iteration that has failed?
(the artifact may still exist even if there have been newer iterations since)
For this type of issue we really do need to understand if the schema is in fact empty, and why.

**Comment by glenxiao** [comment]
Many SchemaGen artifact folders under TFX pipeline_root are empty. To double check, I re-run the job for a few times, and reproduce the same error. It turns out the schema is empty too. Guess this is the cause. In my case, data is ingested from BigQuery, and I run local tests with a small portion of it (add "limit XXX" to the end of BigQuery sql). Though I don't change any data ingestion code (& SQL), BigQuery may potentially return different results. With a relatively small input dataset, SchemaGen may not be able to generate the right schema. Is this a reasonable guess? 
If this is the case, is there any requirement of input dataset for SchemaGen? Want to learn more about how to mitigate this issue in the future.

**Comment by zoyahav** [comment]
@arghyaganguly is it possible to transfer this issue to the tfx repo?
I'm afraid my knowledge of ExampleGen and SchemaGen, where the root cause is, is not sufficient to answer these questions and resolve the issue.
