### ISSUE TITLE
simple example did not work

### ISSUE THREAD

**Issue by joshreuben456** [tensorflow/transform#5]
here is my setup:
```bash
conda create -n tftransform python=2.7
source activate tftransform
pip install tensorflow
pip install tensorflow-transform
pip install dill==0.2.6
git clone https://github.com/tensorflow/transform.git
cd transform/
python setup.py install    # for good measure ...
```

I then try to execute **simple_example**:
`python examples/simple_example.py`

I get the following stacktrace:
```
No handlers could be found for logger "oauth2client.contrib.multistore_file"
Traceback (most recent call last):
  File "examples/simple_example.py", line 64, in <module>
    preprocessing_fn, tempfile.mkdtemp()))
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 439, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/pipeline.py", line 249, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 162, in apply
    return m(transform, input)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 168, in apply_PTransform
    return transform.expand(input)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 597, in expand
    self._output_dir)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 439, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/pipeline.py", line 249, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 162, in apply
    return m(transform, input)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 168, in apply_PTransform
    return transform.expand(input)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 328, in expand
    self._preprocessing_fn, input_schema)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/impl_helper.py", line 416, in run_preprocessing_fn
    inputs = _make_input_columns(schema)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/impl_helper.py", line 218, in _make_input_columns
    placeholders = schema.as_batched_placeholders()
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/tf_metadata/dataset_schema.py", line 87, in as_batched_placeholders
    for key, column_schema in self.column_schemas.items()}
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/tf_metadata/dataset_schema.py", line 87, in <dictcomp>
    for key, column_schema in self.column_schemas.items()}
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/tf_metadata/dataset_schema.py", line 133, in as_batched_placeholder
    return self.representation.as_batched_placeholder(self)
  File "/Users/XXX/anaconda/envs/tftransform/lib/python2.7/site-packages/tensorflow_transform/tf_metadata/dataset_schema.py", line 330, in as_batched_placeholder
    return tf.placeholder(column.domain.dtype,
AttributeError: 'DType' object has no attribute 'dtype'
```

**Comment by elmer-garduno** [comment]
Hi, this looks like a version mismatch to me between what gets installed by using pip package and what's on the Github HEAD?

But I see you are also doing  `python setup.py install` which will presumably install the latest version from head?

Could you please see if the following fixes the problem?

```
python setup.py bdist_wheel
pip install dist/tensorflow_transform-0.1.6dev-py2-none-any.whl
```

We are planning to have a Github and PyPi push by the end of the week. I'll update this thread. 

Sorry for the confusion.

**Comment by joshreuben456** [comment]
@elmer-garduno 
that should actually be 
       `./dist/tensorflow_transform-0.1.6.dev0-py2-none-any.whl`
not `dist/tensorflow_transform-0.1.6dev-py2-none-any.whl`

so, I see this uninstalls `tensorflow-transform-0.1.5` and installs `tensorflow-transform-0.1.6.dev0`

running `python examples/simple_example.py`  now works - I get the following result:
```
[{'s_integerized': 0,
  'x_centered': -1.0,
  'x_centered_times_y_normalized': -0.0,
  'y_normalized': 0.0},
 {'s_integerized': 1,
  'x_centered': 0.0,
  'x_centered_times_y_normalized': 0.0,
  'y_normalized': 0.5},
 {'s_integerized': 0,
  'x_centered': 1.0,
  'x_centered_times_y_normalized': 1.0,
  'y_normalized': 1.0}]
```
 thanks !

**Comment by elmer-garduno** [comment]
Thanks @joshreuben456, both the Github and PyPi repos are now in sync (0.1.6).
