### ISSUE TITLE
All TensorInfo protos used in the SignatureDefs must have the name field set

### ISSUE THREAD

**Issue by ravwojdyla** [tensorflow/transform#70]
Hello.

I getting this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 609, in do_work
    work_executor.execute()
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/executor.py", line 167, in execute
    op.start()
  File "dataflow_worker/native_operations.py", line 38, in dataflow_worker.native_operations.NativeReadOperation.start
    def start(self):
  File "dataflow_worker/native_operations.py", line 39, in dataflow_worker.native_operations.NativeReadOperation.start
    with self.scoped_start_state:
  File "dataflow_worker/native_operations.py", line 44, in dataflow_worker.native_operations.NativeReadOperation.start
    with self.spec.source.reader() as reader:
  File "dataflow_worker/native_operations.py", line 54, in dataflow_worker.native_operations.NativeReadOperation.start
    self.output(windowed_value)
  File "apache_beam/runners/worker/operations.py", line 159, in apache_beam.runners.worker.operations.Operation.output
    cython.cast(Receiver, self.receivers[output_index]).receive(windowed_value)
  File "apache_beam/runners/worker/operations.py", line 85, in apache_beam.runners.worker.operations.ConsumerSet.receive
    cython.cast(Operation, consumer).process(windowed_value)
  File "apache_beam/runners/worker/operations.py", line 392, in apache_beam.runners.worker.operations.DoOperation.process
    with self.scoped_process_state:
  File "apache_beam/runners/worker/operations.py", line 393, in apache_beam.runners.worker.operations.DoOperation.process
    self.dofn_receiver.receive(o)
  File "apache_beam/runners/common.py", line 488, in apache_beam.runners.common.DoFnRunner.receive
    self.process(windowed_value)
  File "apache_beam/runners/common.py", line 496, in apache_beam.runners.common.DoFnRunner.process
    self._reraise_augmented(exn)
  File "apache_beam/runners/common.py", line 537, in apache_beam.runners.common.DoFnRunner._reraise_augmented
    six.raise_from(new_exn, original_traceback)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 718, in raise_from
    raise value
AssertionError: All TensorInfo protos used in the SignatureDefs must have the name field set: dtype: DT_STRING
tensor_shape {
  dim {
    size: -1
  }
  dim {
    size: -1
  }
}
coo_sparse {
  values_tensor_name: "transform/inputs/label/values:0"
  indices_tensor_name: "transform/inputs/label/indices:0"
  dense_shape_tensor_name: "transform/inputs/label/shape:0"
}
```

when running TFT on Dataflow Runner, my `label` in `preprocessing_fn` is a sparse tensor of string. Surpassingly I don't see this error in DirectRunner! I'm using current master version 30146171032ed79ec99ff002ef8f7065c70d8536.

This might be related to https://github.com/tensorflow/tensorflow/issues/6110

If you take a look at `build_tensor_info` (which is used by TFT):

```
@tf_export("saved_model.utils.build_tensor_info")
def build_tensor_info(tensor):
  """Utility function to build TensorInfo proto.

  Args:
    tensor: Tensor or SparseTensor whose name, dtype and shape are used to
        build the TensorInfo. For SparseTensors, the names of the three
        constitutent Tensors are used.

  Returns:
    A TensorInfo protocol buffer constructed based on the supplied argument.
  """
  tensor_info = meta_graph_pb2.TensorInfo(
      dtype=dtypes.as_dtype(tensor.dtype).as_datatype_enum,
      tensor_shape=tensor.get_shape().as_proto())
  if isinstance(tensor, sparse_tensor.SparseTensor):
    tensor_info.coo_sparse.values_tensor_name = tensor.values.name
    tensor_info.coo_sparse.indices_tensor_name = tensor.indices.name
    tensor_info.coo_sparse.dense_shape_tensor_name = tensor.dense_shape.name
  else:
    tensor_info.name = tensor.name
  return tensor_info
```

from TF, for SparseTensor there will be no name set (so that would explain the error) and overall issue, but then again why would that work in DirectRunner? Also what is the recommendation for SparseTensor in `preprocessing_fn`?

Example of Dataflow job: 2018-06-26_10_13_22-11943278300951017592

**Comment by KesterTong** [comment]
This seems like a version mismatch: you are using tensorflow/transform master and I assume a fairly recent version of TF locally, but the version of TF installed in the Dataflow containers may be older.  See https://github.com/tensorflow/transform#compatible-versions

**Comment by harshini-gadige** [comment]
@ravwojdyla  -  Hi, is this still an issue ? Feel free to close this issue if it doesn't exist anymore.

**Comment by harshini-gadige** [comment]
Please try with the relevant version and see if this is still an issue. If so, please post here(we will reopen) or open a new issue with the latest information. Thanks !
