### ISSUE TITLE
AttributeError: 'thread._local' object has no attribute 'state'

### ISSUE THREAD

**Issue by jonathanglima** [tensorflow/transform#85]
I'm having a thread issue with the following code. The traceback and pip freeze are below as well.

I'm on a Mac, running beam locally. Already tested for tensorflow==1.9.0 and had the same error. Any ideas?

### Code
```import tensorflow as tf
import tensorflow_transform as tft
from tensorflow_transform.beam import impl as tft_beam
from tensorflow_transform.tf_metadata import dataset_metadata
from tensorflow_transform.tf_metadata import dataset_schema
import apache_beam as beam

raw_data_metadata = dataset_metadata.DatasetMetadata(
    dataset_schema.from_feature_spec({
        'sku': tf.FixedLenFeature([], tf.string),
}))

categorical_columns = [
    'sku',
]

def preprocessing_tft_fn(inputs):
    for key in categorical_columns:
        tft.vocabulary(inputs[key], vocab_filename=key)

    return inputs

with beam.Pipeline() as p:
    raw_data = (p
        | beam.Create([{'sku': 'a'}, {'sku': 'b'}])
    )

    (transformed_data, transformed_metadata), transform_fn = (
        (raw_data, raw_data_metadata)
        | 'AnalyzeAndTransformTrain' >> tft_beam.AnalyzeAndTransformDataset(preprocessing_tft_fn)
    )
```

### Traceback
```
Traceback (most recent call last):
  File "test.py", line 30, in <module>
    | 'AnalyzeAndTransformTrain' >> tft_beam.AnalyzeAndTransformDataset(preprocessing_tft_fn)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 831, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 488, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/pipeline.py", line 468, in apply
    return self.apply(transform, pvalueish)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/pipeline.py", line 504, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 193, in apply
    return m(transform, input)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 199, in apply_PTransform
    return transform.expand(input)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 862, in expand
    dataset | 'AnalyzeDataset' >> AnalyzeDataset(self._preprocessing_fn))
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 831, in __ror__
    return self.transform.__ror__(pvalueish, self.label)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/transforms/ptransform.py", line 488, in __ror__
    result = p.apply(self, pvalueish, label)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/pipeline.py", line 468, in apply
    return self.apply(transform, pvalueish)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/pipeline.py", line 504, in apply
    pvalueish_result = self.runner.apply(transform, pvalueish)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 193, in apply
    return m(transform, input)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/apache_beam/runners/runner.py", line 199, in apply_PTransform
    return transform.expand(input)
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 717, in expand
    base_temp_dir = Context.create_base_temp_dir()
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 207, in create_base_temp_dir
    state = cls._get_topmost_state_frame()
  File "/Users/jonathangarcialima/.virtualenvs/tft_testing_env/lib/python2.7/site-packages/tensorflow_transform/beam/impl.py", line 200, in _get_topmost_state_frame
    if cls._thread_local.state.frames:
AttributeError: 'thread._local' object has no attribute 'state'
```

### Pip Freeze
```
absl-py==0.5.0
apache-beam==2.6.0
astor==0.7.1
avro==1.8.2
backports.weakref==1.0.post1
boto==2.49.0
cachetools==2.1.0
certifi==2018.8.24
chardet==3.0.4
crcmod==1.7
dill==0.2.8.2
docopt==0.6.2
enum34==1.1.6
fasteners==0.14.1
funcsigs==1.0.2
future==0.16.0
futures==3.2.0
gapic-google-cloud-pubsub-v1==0.15.4
gast==0.2.0
google-api-core==1.5.0
google-api-python-client==1.7.4
google-apitools==0.5.20
google-auth==1.5.1
google-auth-httplib2==0.0.3
google-cloud-bigquery==0.25.0
google-cloud-core==0.25.0
google-cloud-dataflow==2.5.0
google-cloud-pubsub==0.26.0
google-cloud-storage==1.13.0
google-compute-engine==2.8.3
google-gax==0.15.16
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
googledatastore==7.0.1
grpc-google-iam-v1==0.11.4
grpcio==1.15.0
h5py==2.8.0
hdfs==2.1.0
httplib2==0.11.3
idna==2.7
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
Markdown==2.6.11
mock==2.0.0
monotonic==1.5
numpy==1.14.5
oauth2client==4.1.3
pandas==0.23.4
pbr==4.2.0
ply==3.8
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-pubsub-v1==0.15.4
protobuf==3.6.1
psycopg2==2.7.5
pyasn1==0.4.4
pyasn1-modules==0.2.2
pydot==1.2.4
pyparsing==2.2.1
python-dateutil==2.7.3
pytz==2018.4
PyVCF==0.6.8
PyYAML==3.13
requests==2.19.1
retrying==1.3.3
rsa==4.0
sh==1.12.14
six==1.11.0
SQLAlchemy==1.2.12
tensorboard==1.10.0
tensorflow==1.10.0
tensorflow-metadata==0.9.0
tensorflow-transform==0.9.0
termcolor==1.1.0
typing==3.6.6
uritemplate==3.0.0
urllib3==1.23
Werkzeug==0.14.1
```

**Comment by jonathanglima** [comment]
Found the issue. Missing the tft context inside the pipeline:

```
with tft_beam.Context(temp_dir=temp_dir):
```

Sorry for disturbing.

**Comment by derenrich** [comment]
probably would be good to emit a better error message here?

**Comment by jonathanglima** [comment]
I agree. Lost a reasonable amount of time trying to find what the problem was
